"""ajout_champ_openai_api_key

Revision ID: 22e1dbc65341
Revises: 72655609306d
Create Date: 2023-09-16 09:29:39.759286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e1dbc65341'
down_revision = '72655609306d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openai_api_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('openai_api_key')

    # ### end Alembic commands ###
