"""add file model

Revision ID: 597b0927a450
Revises: b1c5b8440868
Create Date: 2023-10-16 18:20:26.668866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597b0927a450'
down_revision = 'b1c5b8440868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    # ### end Alembic commands ###
