"""change a lot of things

Revision ID: 6d64e8c36e37
Revises: 428e5b19e5de
Create Date: 2023-10-10 21:54:40.130348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d64e8c36e37'
down_revision = '428e5b19e5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_information')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.drop_column('mot_de_passe')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mot_de_passe', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('password')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    op.create_table('agent_information',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('objectif', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='agent_information_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='agent_information_pkey')
    )
    # ### end Alembic commands ###
